// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfNu1F_tbwU_RPLrRg3dzM2ctkKUpCMd8',
    appId: '1:537210548197:web:3008c67fdd96cb8683890c',
    messagingSenderId: '537210548197',
    projectId: 'fir-coba-be7a1',
    authDomain: 'fir-coba-be7a1.firebaseapp.com',
    storageBucket: 'fir-coba-be7a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlHojDCRMlFR7jI9OWZWbLyluewQREtkc',
    appId: '1:537210548197:android:1e1d55edd5570c5e83890c',
    messagingSenderId: '537210548197',
    projectId: 'fir-coba-be7a1',
    storageBucket: 'fir-coba-be7a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDyFgFCuEJvrvxF4HD6p6Z-y9E1s4IF5A',
    appId: '1:537210548197:ios:206118470857b22383890c',
    messagingSenderId: '537210548197',
    projectId: 'fir-coba-be7a1',
    storageBucket: 'fir-coba-be7a1.appspot.com',
    iosClientId: '537210548197-hgdmobs3oip41c5ouks002dkcle3t3lt.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );
}
